site_name: Nexus Alpha Database
site_description: Wiki oficial do projeto Nexus Alpha
site_url: https://nexus-alpha.pages.dev

theme:
  name: material
  language: pt
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.share
    - content.code.copy
  palette:
    - scheme: slate
      primary: purple
      accent: cyan

nav:
  - Início: index.md
  - Personnel Files: personnel/index.md
  - Lore: lore/index.md
  - Clearance Levels: clearance.md
  - ⌬ Organic Synthesis Division: osd.md

plugins:
  - search
